### ISSUE TITLE
오류 문의 드립니다.

### ISSUE THREAD

**Issue by byisak** [Giftland/Happymoney-API#1]
안녕하세요. 

해피머니에서 api를 실행하는데 index.js에 아이디및 암호를 입력한후  아래와 같은 에러 메시지가 출력이 됩니다.

다른 설정해야하는 부분이 따로 또 있는건가요? 확인 부탁드립니다. 

> happymoney-api@1.0.0 start
> tsc && node ./dist/index.js

(node:25385) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/var/www/Happymoney/dist/happymoney.js:41
            success: loginResult.result.success === "Y",
                                        ^

TypeError: Cannot read properties of undefined (reading 'success')
    at Happymoney.login (/var/www/Happymoney/dist/happymoney.js:41:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/Happymoney/dist/index.js:9:19

Node.js v21.7.1

**Comment by DollarNoob** [comment]
해피머니 모바일웹 로그인 페이지의 비밀번호 입력란에 키보드보안이 적용되어 모듈의 로그인 부분 코드를 수정하였습니다.
1.0.3 버전으로 다시 시도해 주세요.
